BeerOverflow/BeerOverflow/Controllers/BeerTypesController.cs
using BeerOverflow.Database;
using BeerOverflow.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace BeerOverflow.Web.Controllers
{
    public class BeerTypesController : Controller
    {
        private readonly BeerOverflowContext _context;

        public BeerTypesController(BeerOverflowContext context)
        {
            _context = context;
        }

        // GET: BeerTypes
        public async Task<IActionResult> Index(string currentFilter, string searchString, int? pageNumber)
        {
            var beerTypes = _context.BeerTypes
                .Where(b => !b.IsDeleted).AsQueryable();
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            if (!string.IsNullOrEmpty(searchString))
            {
                beerTypes = beerTypes.Where(b => b.Name.ToLower().Contains(searchString.ToLower()));
            }
            int pageSize = 12;
            return View(await PaginatedList<BeerType>.CreateAsync(beerTypes, pageNumber ?? 1, pageSize));
        }

        // GET: BeerTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beerType = await _context.BeerTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (beerType == null)
            {
                return NotFound();
            }

            return View(beerType);
        }

        // GET: BeerTypes/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: BeerTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,CreatedOn,ModifiedOn,IsDeleted,DeletedOn")] BeerType beerType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(beerType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(beerType);
        }
        private bool BeerTypeExists(int id)
        {
            return _context.BeerTypes.Any(e => e.Id == id);
        }
    }
}

BeerOverflow/BeerOverflow/Controllers/BeersController.cs
using BeerOverflow.Database;
using BeerOverflow.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeerOverflow.Web.Controllers
{
    public class BeersController : Controller
    {
        private readonly BeerOverflowContext _context;

        public BeersController(BeerOverflowContext context)
        {
            _context = context;
        }

        // GET: Beers
        public async Task<IActionResult> Index(string currentFilter, string searchString, int? pageNumber)
        {

            var beers = _context.Beers
                .Where(b => !b.IsDeleted)
                .Include(b => b.Brewery)
                .Include(b => b.Type).AsQueryable();

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            if (!string.IsNullOrEmpty(searchString))
            {
                beers = beers.Where(b => b.Name.ToLower().Contains(searchString.ToLower())
                                       || b.Brewery.Name.ToLower().Contains(searchString.ToLower())
                                       || b.Type.Name.ToLower().Contains(searchString.ToLower())).AsQueryable();
            }
            int pageSize = 12;
            return View(await PaginatedList<Beer>.CreateAsync(beers, pageNumber ?? 1, pageSize));
        }
        // GET: Beers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _context.Beers
                .Include(b => b.Brewery)
                .Include(b => b.Type)
                .Include(b => b.Likes)
                .Include(b => b.Reviews)
                .ThenInclude(r => r.Author)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (beer == null)
            {
                return NotFound();
            }

            return View(beer);
        }

        // GET: Beers/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["BreweryId"] = new SelectList(_context.Breweries, "Id", "Name");
            ViewData["TypeId"] = new SelectList(_context.Set<BeerType>(), "Id", "Name");
            return View();
        }

        // POST: Beers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,TypeId,BreweryId,CreatedOn,DeletedOn,ModifiedOn,IsDeleted,AlcoholByVolume")] Beer beer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(beer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BreweryId"] = new SelectList(_context.Breweries, "Id", "Name", beer.BreweryId);
            ViewData["TypeId"] = new SelectList(_context.Set<BeerType>(), "Id", "Name", beer.TypeId);
            return View(beer);
        }
        public IActionResult CreateReview(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            return RedirectToAction("Create", "Reviews", new { id = Id });
        }

        public IActionResult EditReview(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            return RedirectToAction("Edit", "Reviews", new { id = Id });
        }
        [Authorize]
        public IActionResult AddToWishlist(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var user = _context.Users.FirstOrDefault(u => u.UserName == HttpContext.User.Identity.Name);
            var beer = _context.Beers.FirstOrDefault(b => b.Id == Id);
            var wishlistExists = _context.WishlistBeers.FirstOrDefault(l => l.UserId == user.Id && l.BeerId == Id);
            if (wishlistExists == null)
            {
                var wishlist = new WishlistBeer
                {
                    UserId = user.Id,
                    User = user,
                    BeerId = (int)Id,
                    Beer = beer
                };
                _context.WishlistBeers.Add(wishlist);
                _context.SaveChanges();
            }
            return RedirectToAction("Index", "WishlistBeers");
        }
        [Authorize]
        public IActionResult AddToBeersDrank(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var user = _context.Users.FirstOrDefault(u => u.UserName == HttpContext.User.Identity.Name);
            var beer = _context.Beers.FirstOrDefault(b => b.Id == Id);
            var beerDrankExists = _context.BeersDrank.FirstOrDefault(l => l.UserId == user.Id && l.BeerId == Id);
            if (beerDrankExists == null)
            {
                var beerDrank = new BeerDrank
                {
                    UserId = user.Id,
                    User = user,
                    BeerId = (int)Id,
                    Beer = beer
                };
                _context.BeersDrank.Add(beerDrank);
                _context.SaveChanges();
            }
            return RedirectToAction("Index", "BeersDrank");
        }
        [Authorize]
        public IActionResult Like(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var user = _context.Users.FirstOrDefault(u => u.UserName == HttpContext.User.Identity.Name);
            var beer = _context.Beers.FirstOrDefault(b => b.Id == Id);
            var likeExists = _context.Likes.FirstOrDefault(l => l.UserId == user.Id && l.BeerId == Id);
            if(likeExists == null)
            {
                var like = new Like
                {
                    UserId = user.Id,
                    User = user,
                    BeerId = (int)Id,
                    Beer = beer
                };
                _context.Likes.Add(like);
            }
            else
            {
                _context.Likes.Remove(likeExists);
            }
            _context.SaveChanges();
            return RedirectToAction("Details", new { id = Id });
        }

        private bool BeerExists(int id)
        {
            return _context.Beers.Any(e => e.Id == id);
        }
    }
}

BeerOverflow/BeerOverflow/Controllers/BreweriesController.cs
using BeerOverflow.Database;
using BeerOverflow.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace BeerOverflow.Web.Controllers
{
    public class BreweriesController : Controller
    {
        private readonly BeerOverflowContext _context;

        public BreweriesController(BeerOverflowContext context)
        {
            _context = context;
        }

        // GET: Breweries
        public async Task<IActionResult> Index(string currentFilter, string searchString, int? pageNumber)
        {
            var breweries = _context.Breweries
                .Where(b => !b.IsDeleted)
                .Include(b => b.Country).AsQueryable();

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            if (!string.IsNullOrEmpty(searchString))
            {
                breweries = breweries.Where(b => b.Name.ToLower().Contains(searchString.ToLower())
                                       || b.Country.Name.ToLower().Contains(searchString.ToLower()));
            }
            int pageSize = 12;
            return View(await PaginatedList<Brewery>.CreateAsync(breweries, pageNumber ?? 1, pageSize));
        }

        // GET: Breweries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brewery = await _context.Breweries
                .Include(b => b.Country)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brewery == null)
            {
                return NotFound();
            }

            return View(brewery);
        }

        // GET: Breweries/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "Name");
            return View();
        }

        // POST: Breweries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,CountryId,IsDeleted,DeletedOn,CreatedOn,ModifiedOn")] Brewery brewery)
        {
            if (ModelState.IsValid)
            {
                _context.Add(brewery);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "Name", brewery.CountryId);
            return View(brewery);
        }
        private bool BreweryExists(int id)
        {
            return _context.Breweries.Any(e => e.Id == id);
        }
    }
}

BeerOverflow/BeerOverflow/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
    @ViewData["Title"] - BeerOverflow
    </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img src="~/images/icon.png" width="40" , height="40" />
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BeerOverflow</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Beers" asp-action="Index">Beers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="BeerTypes" asp-action="Index">BeerTypes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Breweries" asp-action="Index">Breweries</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Reviews" asp-action="Index">Reviews</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Beers" asp-action="Index">Beers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="BeerTypes" asp-action="Index">BeerTypes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Breweries" asp-action="Index">Breweries</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reviews" asp-action="Index">Reviews</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BeerOverflow - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>